name: "Publish to pypi"

on:
  workflow_call:
    inputs:
      py-version:
        required: false
        type: string
        default: "3.x"

jobs:
  publish:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ inputs.py-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.py-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
